### ISSUE TITLE
Not possible to use with Firefox

### ISSUE THREAD

**Issue by franden** [FarmGeek4Life/NegotiateSSO#7]
We use your plugin with our Jenkins installation. Unfortunately it does not work with current version of Firefox out of the box. Only if we use this plugin  "https://addons.mozilla.org/en-US/firefox/addon/integrated-auth-for-firefox/" and the Jenkins URL is added there SSO works.

Without this plugin it is not possible to login with Firefox at all. Though the "Authentication Packages" package is set to "Negotiate then Basic" after entering the credentials the BASIC login mask appears again and again. In the error log file there is this message :

Oct 12, 2016 7:28:02 AM waffle.servlet.NegotiateSecurityFilter doFilter
WARNING: error logging in user: com.sun.jna.platform.win32.Win32Exception: The handle specified is invalid 

Is it an issue with the plugin or with our infrastructure? please help.

**Comment by FarmGeek4Life** [comment]
That plugin helps manage settings that must be changed in Firefox to allow SPNEGO/Kerberos authentication. There are ways of configuring those settings without the plugin (see [here](https://ping.force.com/Support/PingFederate/Integrations/How-to-configure-supported-browsers-for-Kerberos-NTLM) and [here](https://developer.mozilla.org/en-US/docs/Mozilla/Integrated_authentication), and they encourage IT departments to configure those settings - [this site](https://jamfnation.jamfsoftware.com/discussion.html?id=13345) has some information about doing so.

If automatic authentication works fine in Internet Explorer and Chrome, then that setting is the first solution; another change you may need to make (depending on the settings in Firefox) is adding a redirect URL and enabling in the the NegotiateSSO plugin settings, so that the plugin always forces the fully qualified domain name.

**Comment by franden** [comment]
thank you for your fast answer. Usage of the plugin is a possible solution for us.

Another solution is to use BASIC authentication for the Firefox user. If we do not use the plugin and want to use the fallback BASIC authentication, how we can avoid that the BASIC authentication mask appears again and again? There a two different dialog that appear if the user tries to visit with the firefox browser. The first one has the text: "Please enter your user name and password for http://....." the second have this text "http://..... needs user name and password. Output from the website: BasicSecurityFilterProvider". 
The authentication works only in the second authentication dialog. Can we avoid the first authentication dialog?

**Comment by FarmGeek4Life** [comment]
The first login pop-up is caused by the authentication fallback mechanism
of the negotiate protocol - because Kerberos authentication was not
available, it falls back on NTLM, which then triggers a login prompt since
NTLM credentials aren't available; after that fails, then the basic
authentication appears, which does work. Unfortunately there is no easy way
on Windows to disable the NTLM fallback of the negotiate protocol, and I'm
not sure if changing the "protocols" setting for the plugin from
"Negotiate, fallback on NTLM" to "Negotiate only" will fix the problem you
are seeing.

**Comment by franden** [comment]
Changing the "protocols" setting for the plugin from "Negotiate, fallback on NTLM" to "Negotiate only" fixed the problem. Now only the second authentication dialog appears and the Firefox users can successfully login. Great! Thank you.

**Comment by jiniguez** [comment]
We are finding the same when using Firefox and with Explorer/Chrome and trying to log in from machines that are not registered in the domain, so they can't use Kerberos and have to fallback to NTLM.

Checking the code we found out the exception is originated here:

https://github.com/FarmGeek4Life/NegotiateSSO/blob/master/src/main/java/com/github/farmgeek4life/jenkins/negotiatesso/WindowsAuthForJenkins.java#L80

After accepting the token from the client browser, it tries to obtain the user's identity from the context but this is not working with NTLM authentication.  The problem is that user identity is not available in the first request because NTLM needs 2 requests to complete the authentication negotiation, so an invalid handle exception is raised and the negotiation stops there because of the exception being thrown. 

I have created a pull request #8 that seems to fix the issue in our installation.

**Comment by FarmGeek4Life** [comment]
The pull request from @jiniguez does allow NTLM to work in the scenario he describes, and should also allow it to work in the scenario @franden describes, without the endless login popups. After this change is included in a release, it would be preferable to re-enable NTLM protocol if you do not have HTTPS configured for your jenkins server (because the basic authentication provider passes passwords in plaintext over the network, if I remember correctly).
